adb shell pm uninstall -k --user 0 com.realmestore.app
adb shell pm uninstall -k --user 0 com.coloros.karaoke
adb shell pm uninstall -k --user 0 com.heytap.pictorial
adb shell pm uninstall -k --user 0 com.heytap.cloud
adb shell pm uninstall -k --user 0 com.heytap.music
adb shell pm uninstall -k --user 0 com.heytap.market
adb shell pm uninstall -k --user 0 com.finshell.fin
adb shell pm uninstall -k --user 0 com.heytap.openid
adb shell pm uninstall -k --user 0 com.nearme.statistics
adb shell pm uninstall -k --user 0 com.coloros.phonenoareainquire
adb shell pm uninstall -k --user 0 com.facebook
adb shell pm uninstall -k --user 0 com.facebook.system
adb shell pm uninstall -k --user 0 com.facebook.services
adb shell pm uninstall -k --user 0 com.facebook.app
adb shell pm uninstall -k --user 0 com.facebook.appmanager
adb shell pm uninstall -k --user 0 com.google.android.apps.restore
adb shell pm uninstall -k --user 0 com.coloros.gallery3d
adb shell pm uninstall -k --user 0 com.heytap.cast
adb shell pm uninstall -k --user 0 com.coloros.childrenspace
adb shell pm uninstall -k --user 0 com.coloros.floatassistant
adb shell pm uninstall -k --user 0 com.nearme.romupdate
adb shell pm uninstall -k --user 0 com.facebook.katana
adb shell pm uninstall -k --user 0 com.heytap.datamigration
adb shell pm uninstall -k --user 0 com.coloros.safecenter
adb shell pm uninstall -k --user 0 com.coloros.gamespaceui
adb shell pm uninstall -k --user 0 com.coloros.phonemanager
adb shell pm uninstall -k --user 0 com.heytap.browser
adb shell pm uninstall -k --user 0 com.google.android.feedback
adb shell pm uninstall -k --user 0 com.coloros.calculator
adb shell pm uninstall -k --user 0 com.coloros.lockassistant
adb shell pm uninstall -k --user 0 com.coloros.compass2
adb shell pm uninstall -k --user 0 com.coloros.weather2
adb shell pm uninstall -k --user 0 com.coloros.sau
adb shell pm uninstall -k --user 0 com.coloros.transalte.engine
adb shell pm uninstall -k --user 0 com.coloros.translate.engine
adb shell pm uninstall -k --user 0 com.coloros.smartdrive
adb shell pm uninstall -k --user 0 com.google.android.apps.wellbeing
adb shell pm uninstall -k --user 0 com.realme.wellbeing
adb shell pm uninstall -k --user 0 com.realme.securitycheck
adb shell pm uninstall -k --user 0 com.coloros.screenrecorder
adb shell pm uninstall -k --user 0 com.coloros.eyeprotect
adb shell pm uninstall -k --user 0 com.coloros.oshare
adb shell pm uninstall -k --user 0 com.coloros.locationproxy
adb shell pm uninstall -k --user 0 com.coloros.activation
adb shell pm uninstall -k --user 0 com.heytap.usercenter
adb shell pm uninstall -k --user 0 com.coloros.focusmode
adb shell pm uninstall -k --user 0 com.coloros.gamespace
adb shell pm uninstall -k --user 0 com.coloros.gamespaceui
adb shell pm uninstall -k --user 0 com.oppo.operationManual
adb shell pm uninstall -k --user 0 com.google.ar.core
adb shell pm uninstall -k --user 0 com.google.ar.lens
adb shell pm uninstall -k --user 0 com.ted.number
adb shell pm uninstall -k --user 0 com.google.android.apps.tachyon
adb shell pm uninstall -k --user 0 com.coloros.securitykeyboard
adb shell pm uninstall -k --user 0 com.oppo.sos
adb shell pm uninstall -k --user 0 com.coloros.sauhelper
adb shell pm uninstall -k --user 0 com.realme.movieshot
adb shell pm uninstall -k --user 0 com.coloros.soundrecorder
adb shell pm uninstall -k --user 0 com.coloros.filemanager
adb shell pm uninstall -k --user 0 com.coloros.video
adb shell pm uninstall -k --user 0 com.coloros.ocrservice
adb shell pm uninstall -k --user 0 com.google.android.gms.location.history
adb shell pm uninstall -k --user 0 com.google.android.gms.location.history
adb shell pm uninstall -k --user 0 com.google.android.apps.photos
adb shell pm uninstall -k --user 0 com.google.android.projection.gearhead
adb shell pm uninstall -k --user 0 com.google.android.mainline.telemetry
adb shell pm uninstall -k --user 0 com.google.mainline.telemetry
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.coloros.ocrscanner
adb shell pm uninstall -k --user 0 com.coloros.alarmclock
adb shell pm uninstall -k --user 0 com.coloros.securepay
adb shell pm uninstall -k --user 0 com.coloros.logkit
adb shell pm uninstall -k --user 0 com.coloros.smartsidebar
adb shell pm uninstall -k --user 0 com.coloros.encryption
adb shell pm uninstall -k --user 0 com.oppo.quicksearchbox
adb shell pm uninstall -k --user 0 com.oppo.qualityprotect
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall -k --user 0 com.redteamobile.roaming
adb shell pm uninstall -k --user 0 com.nearme.gamecenter
adb shell pm uninstall --user 0 com.nearme.gamecenter
adb shell pm uninstall --user 0 com.nearme.gamecenter
adb shell pm uninstall -k --user 0 com.coloros.assistantscreen
